name: Test

on: 
  pull_request:
    types: ["opened", "closed", "reopened"]
  pull_request_review:
    types: "submitted"
  pull_request_review_comment:
    types: "created"

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Update notion status
        uses: subhroacharjee/my-test-action@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          event: ${{ toJSON(github.event) }}
          token: ${{ secrets.GITHUB_TOKEN }}
