name: Test

on: 
  pull_request:
    types: "*"

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Annotate PR
        uses: MathGaps/notion-issue-sync@main
        with:
          webhook: ${{ secrets.GITHUB_WEBHOOK}}
          event: ${{ github.event }}
          token: ${{ secrets.GITHUB_TOKEN }}
